[package]
name = "parser-dump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sddms-shared = { path = '../sddms-shared' }
sqlparser = "0.40.0"